name: dillinger
version: '0.1.0'
summary: The last Markdown editor, ever
description: |
  Dillinger is a cloud-enabled, mobile-ready, offline-storage, AngularJS powered
  HTML5 Markdown editor.

apps:
  dillinger:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/dillinger
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl

parts:
  electron-app:
    plugin: nodejs
    source: app/

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio

    after:
      - desktop-glib-only

    prepare: |
      npm install electron --save-dev --save-exact
      npm install electron-builder --save-dev
    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
